a=input("Enter value for a: ")
b=input("Enter value for b: ")
sum=int(a)+int(b)
b=int(sum)-int(b)
a=int(sum)-int(b)
print("Value of x after swap is: ")
print(a)
print("Value of y after swap is: ")
print(b)